user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 768;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    #access_log /var/log/nginx/access.log;
    #error_log /var/log/nginx/error.log;

    access_log /dev/stdout;
    error_log /dev/stderr;

    server {
        listen 443 ssl;
        server_name abourrich.42.fr;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        root /var/www/html;
        index index.php index.html;

        # WordPress multisite subdirectory rules
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # WordPress multisite subdirectory rules
        location ~ ^/[_0-9a-zA-Z-]+/wp-admin/ {
            rewrite ^/[_0-9a-zA-Z-]+/wp-admin/(.*) $1 break;
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        # Deny access to . files
        location ~ /\. {
            deny all;
        }

        # Deny access to wp-config.php
        location = /wp-config.php {
            deny all;
        }
    }
} 